// app/layout.jsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "@/component/navbar/page";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { CourseProvider } from "./contextApi/page";
import Navbar from "@/component/navbar/page";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navList = [
  { label: "Home", href: "/" },
  { label: "Contact us", href: "/contact-us" },
  { label: "About", href: "/about" },
  { label: "Log in", href: "/" },
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-amber-100`}
      >
        <CourseProvider>
          <Navbar navList={navList} />
          <Toaster className="swiper-centered" />
          <main>{children}</main>
        </CourseProvider>
      </body>
    </html>
  );
}
