import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/page";
import Caraousel from "@/component/carousels/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navList = [
  { label: "Home", href: "/" },
  { label: "Contact us", href: "/contact-us" },
  { label: "About", href: "/about" },
  { label: "Log in", href: "/login" },
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar navList={navList} />
        <Caraousel />
      </body>
    </html>
  );
}
